version: 2
updates:
  # Maintain dependencies for go
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "ok-to-test"
      - "release-note-none"
    groups:
      kubernetes:
        patterns:
          - "k8s.io/*"
    ignore:
      # Ignore major and minor versions for dependencies updates
      # Allow patches and security updates.
      - dependency-name: k8s.io/*
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      # TODO: remove this until https://github.com/open-policy-agent/cert-controller/issues/207 is fixed.
      - dependency-name: sigs.k8s.io/controller-runtime
