apiVersion: v1
kind: Service
metadata:
  name: llamacpp-llama3-8b-instruct-bartowski-q5km
spec:
  selector:
    app: llamacpp-llama3-8b-instruct-bartowski-q5km
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
